apiVersion: v1
kind: Service
metadata: 
  namespace: shopping
  name: shopping
spec: 
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    apps.kubernetes.io/name: shopping ## RBAC 형식이 다르면 Target Group이 안붙음..
