apply:
	kubectl apply -f ./ns/namespace.yaml
	kubectl apply -f ./dep/deployment.yaml
	kubectl apply -f ./svc/service.yaml
	kubectl apply -f ./ingress/ingress.yaml

delete:
	kubectl delete -f ./ingress/ingress.yaml
	kubectl delete -f ./svc/service.yaml
	kubectl delete -f ./dep/deployment.yaml
	kubectl delete -f ./ns/namespace.yaml
	